### ISSUE TITLE
m29 standalone system errors

### ISSUE THREAD

**Issue by EdmundCampion** [CNMAT/CNMAT-MMJ-Depot#60] opened 2015-02-09 18:24 UTC
I have had some strange bug behavior on my Mac OS Lion.  I tried opening several MU29 standalones and got the error "mixerengine already in use".  Then I saw the same error when I opened Max 6.  After restarting computer and throwing all preferences from Max and audio midi etc.. I opened the standalones and they crashed immediately on opening.  I post the log of one of those crashes below.  

Thing is, I went back to a different 2013 version of the standalones and they work fine.  The creation date on each paired standlone is the same.  I think some of this is my computer audio driver -- but I don't know how to reinstall those drivers.  

(log in gist)

**Comment by equilet** [comment] 2015-02-09 22:11
https://gist.github.com/equilet/15031a3d8ef867ff83e0

**Comment by equilet** [comment] 2015-02-09 22:12
Is this also happening in the labs?
What are the specs of those machines?

What version of Max or Max runtime?

**Comment by mattschumaker** [comment] 2015-02-09 22:34
@equilet 

I don't think that I have experienced this particular error in lab. To the best of my knowledge, I have not seen the error: "mixerengine already in use."  

However, I copied you this morning on an email to Willa about an error I have witnessed over the last two labs.  The error manifests as "spinning wheel"/crashed program. This effects c. 5-7% of lab computers for any given patch that is opened, so c.2 machines of 35 per patch.  The problem is erratic in the sense that it doesn't seem to repeatedly target specific lab machines and in the sense that the software works for the majority of the users at any one time, suggesting to me that the problem might not be in the given standalone applications. But maybe I'm wrong about that. At one point, Willa suggested that it might have something to do with memory allocation on the lab machines.  The only temporary fix we have adopted so far is to have GSIs pass new copies of the standalone from their share folder to affected students. This seems to work most but not all of the time. 

I don't have the specs of the lab machines on me and I don't know the version of Max runtime.  We have not been using Max in class yet. I can send easily send specs info to you tomorrow, if you need them.

**Comment by equilet** [comment] 2015-02-09 22:38
OK, since that kinda freaks me out I'm going to pretend it's Willa's issue until I hear otherwise.  Will follow up w/ Ed on the 'mixerengine already in use' thing - Ed, have you verified that you are always opening the standalone up with the correct application (listed in getinfo)?

**Comment by EdmundCampion** [comment] 2015-02-09 23:38
The error message reads:  mixerengine_new: ##mixerengineinstance## is in use!
I can bring in both standalones and show in Wednesday...

I have two of them with the same creation date.  My hunch is this has something to do with Quicktime and using the 8-channel mix in quicktime --

**Comment by ilzxc** [comment] 2015-02-10 02:16
The problem with lab machines is more than the % provided, I have around 10 machines spinning wheels.  And they sometimes start spinning wheels after not spinning originally, which may be a hint...

I find it suspect that (a) I had NO ISSUES on the instructor machine, and (b) that the problem is as erratic as it is. I would recommend looking at "top" in the terminal and look at memory. I will do this next time I'm at the lab - the weird delayed nature of the problem hints at an issue that is extremely challenging to track. 

Thanks a lot for the remarkable work with standalones. These issues come up and things are hard, but I think we have the best ones I've seen yet and I'm very grateful for your work. Instructor machine, at least, is rocking them solid without a single (!!!) crash or issue, across three hours of lab time, with everything turned on. 

Thanks,


Ilya

**Comment by equilet** [comment] 2015-02-10 02:25
Thanks for the feedback.
It wouldn't kill me to rebuild all of them, but if you can narrow the issue down a bit, it'd be greatly appreciated - LMK about your findings w/ `top` and if you have specific steps to reproduce, that'd also be helpful.  I need details like the following:

1. what OS
2. what version of runtime or Max
3. what version of the standalones (or where you got them)
4. what created date of the files you're loading
5. which apps this is an issue on (or is it all of them?)
6. specs of the Mac computers running these

To be honest, the issues Ilya/Matt are mentioning sound a bit unrelated to Ed's problem, so any clarification would be great.

**Comment by mattschumaker** [comment] 2015-02-10 05:59
The percentage I meant to give was an estimate of afflicted computers at any given moment, usually with one standalone. In other words up to about 3 computers could be having spinning wheel issues at any given time. So, 10+ computers total could be affected over the course of a lab but not at the same time. This is what I observed in two sessions of the previous lab on different days.

Ilya did you experience a higher percentage, like 30% malfunctiong computers at any given moment, on this most recent lab? Or did you experience 10 computers each having temporary spinning wheel issues at different times over the course of the whole lab?  

Thanks,
Matt

**Comment by mattschumaker** [comment] 2015-02-10 06:05
Hi Jeff,
I can look up this information in lab tomorrow afternoon.

**Comment by EdmundCampion** [comment] 2015-02-10 18:24
agreed that these are separate issues --

**Comment by mattschumaker** [comment] 2015-02-12 18:49
@equilet
Hi Jeff,

Following up here from our exchange earlier this week.  Willa told me this morning that, within the next couple of days, their specialist will test with our software in the Wheeler lab to try and determine whether or not it is a lab issue.  They suspect that it is not a memory issue in the lab because larger programs, such as Illustrator, seem to be working fine on their machines. I offered to be there to demonstrate the use of the programs, so hopefully I will be able to witness this testing. I'm not sure yet if they plan to let me be there.

Here below are some answers to your specs questions.  Thanks.



Information taken from a student lab machine.
    
what OS: 
10.9.5

what version of runtime or Max:  
The standalones are self-contained and don't use runtime or Max, is that correct? However, the application Max6 is available on the student machines.

what version of the standalones (or where you got them): 
The standalones were originally taken from Ed's large hard drive. It is generally kept in his mailbox at CNMAT.
Where do I find the version number for the standalones? Do you want the version numbers of all the applications or is there a version number for the whole package? Each applications seems to have a different one. For instance, Soundfile Presenter is ver. 1, Temporal Beat Slicer is 1.1, and Soundfile Interp Space is version 0.1a.  

what created date of the files you're loading:
These dates are taken from the lab folders:
Labs 1-2, 7-12 is Jan 22, 2015
Lab 3+6, is Feb 5, 2015
Labs 4+5, 2015

which apps this is an issue on (or is it all of them?):
Lab 1 with Soundfile Presenter seemed to go smoothly.  Labs 2-3 have experienced significant spinning wheel, hanging program issues. Lab 4 has not happened yet but we expect similar issues since it involves the same software as Lab 3.

specs of the Mac computers running these:
iMac, late 2012
Processor: 2.9 GHz intel Core i5
Memory: 8 gb 1600 MHz DDR3
Graphics card: NVIDIA Gforce GXT 660M 512 MB
Software: Os x 10.9.5

Thanks.

**Comment by mattschumaker** [comment] 2015-02-12 21:51
@equilet
Hi Jeff, just writing to let you know that I was able to meet briefly with the person at Wheeler lab in charge of pushing the software out to the lab computers.  I explained to him all of the issues that we have been experiencing.  He was still testing with our software when I had to leave to go to Music 29 lecture this morning, but I assume that we will hear more from them soon.

**Comment by mattschumaker** [comment] 2015-02-13 19:03
@equilet

Hi Jeff,
Lab standalone applications seem to have vastly improved performance if you make a significant change.  Whenever students open any lab standalone, we now instruct them to:

1) Open Audio status window and in this window:
2) Change i/o vector size to 512
3) Also, change signal vector size to 512

Most standalones seem to start with setting of 64 for both i/o vector size and signal vector size.

I was with Rafael in lab this morning and we saw that with these new settings we went from 10 malfunctioning computers to none malfunctioning with the Soundfile Interpolation patch.  Audition and Decide I standalone had similar results.  Rafael was the first to realize that changing these settings might help. We will continue to observe this.  We're hoping that these changes will resolve the issues we have seen so far.

If it is the case, will it be possible to program the future patches to start automatically with higher i/o and signal vector sizes?

Thanks for your time with this.  Please write back so that I know that this message got to you.

Best,
Matt

**Comment by equilet** [comment] 2015-02-13 19:24
this is the wrong issue thread.  I'm moving all comments to a new thread - stay tuned.

**Comment by equilet** [comment] 2015-02-13 19:29
@EdmundCampion  - please verify that your issue is fixed based on our solution the other day.
If so, please close this out.

**Comment by EdmundCampion** [comment] 2015-02-13 19:55
All our mu29 patches should come with a DSP loadbang -- so that future standalone builds don't have this problem...

**Closed** 2015-02-13 20:04 UTC
Labels: high priority
